now we're talkin

diff --git a/wenv b/wenv
--- a/wenv
+++ b/wenv
@@ -1,14 +1,12 @@
 #!/usr/bin/env zsh
 
-wenv_def() {
-    WENV_DIR="$SRC/wenv"
-    WENV_DEPS=()
-    WENV_EXTENSIONS=('c')
+wenv_dir="$SRC/wenv"
+wenv_deps=()
+wenv_extensions=('c')
 
-    bootstrap_wenv() {}
-    startup_wenv() {}
-    shutdown_wenv() {}
-}
+bootstrap_wenv() {}
+startup_wenv() {}
+shutdown_wenv() {}
 
 export WENV_CFG="${XDG_CONFIG_HOME:-$HOME/.config}/wenv"
 
@@ -28,7 +26,7 @@ SUBCOMMANDS
   edit <wenv>           Edit the wenv file for <wenv>.
   rename <old> <new>    Rename wenv <old> to <new>.
   remove <wenv>         Delete the wenv file for <wenv>.
-  source <wenv>         Source <wenv>'s environment (excluding its wenv_def).
+  source <wenv>         Source the wenv file for <wenv>.
   cd <wenv>             Change to <wenv>'s base directory.
   extension <cmd>       Interact with wenv extensions.
   bootstrap <wenv>      Run <wenv>'s bootstrap function.
@@ -181,24 +179,69 @@ OPTIONS
 }
 
 wenv_exec() {
-    local flag_c=1
-
-    local opt OPTIND
-    while getopts ":c" opt; do
-        case $opt in
-            c) flag_c=0 ;;
-        esac
-    done
-    shift $((OPTIND-1))
-
     [[ -z "$1" ]] && return 1
     export WENV="$1"
 
     wenv_source || { echo "failed to source wenv '$WENV'" >&2 ; return 1 }
 
-    ((flag_c == 1)) && cd "$WENV_DIR" &> /dev/null
+    cd "$wenv_dir" &> /dev/null
 
     return 0
+}
+
+wenv_source() {
+    local usage="\
+USAGE
+  wenv source [-h] [<wenv>, ...] - Source active wenv + its dependencies.
+
+OPTIONS
+  -h    Display this help message.
+
+DESCRIPTION
+  \`wenv source\` sources the active wenv's aliases and its dependencies.
+"
+
+    [[ -z "$WENV" ]] && { echo "error sourcing active wenv: \$WENV is empty" >&2 ; return 1 }
+
+    local opt OPTIND
+    while getopts ":h" opt; do
+        case "$opt" in
+            h)
+                echo "$usage"
+                return 0
+                ;;
+            \?)
+                echo "unknown option: -$OPTARG" >&2
+                return 1
+                ;;
+        esac
+    done
+
+    only_load_wenv_vars=1 source $WENV_CFG/wenvs/$WENV
+
+    export WENV_DIR=$wenv_dir
+    export WENV_DEPS=$wenv_deps
+    export WENV_EXTENSIONS=$wenv_extensions
+
+    ((${#WENV_EXTENSIONS[@]} != 0)) && wenv_extension_load "${WENV_EXTENSIONS[@]}"
+    ((${#WENV_DEPS[@]} != 0)) && source_wenv_dependencies_recursively "${WENV_DEPS[@]}"
+
+    source $WENV_CFG/wenvs/$WENV
+
+    return 0
+}
+
+source_wenv_dependencies_recursively() {
+    local wenv
+    for wenv in $@; do
+        unset_quiet wenv_deps
+
+        only_load_wenv_vars=1 source "$WENV_CFG/wenvs/$wenv"
+        eval source_wenv_dependencies_recursively $wenv_deps
+
+        # source this wenv now that its dependencies are loaded
+        source $WENV_CFG/wenvs/$wenv
+    done
 }
 
 wenv_stop() {
@@ -249,29 +292,13 @@ wenv_clean_up() {
     [[ -z "$WENV" ]] && return 1
 
     unset_quiet WENV
-    unset_wenv_vars
+    unset_quiet WENV_{DIR,DEPS,EXTENSIONS}
     unset_quiet -f {bootstrap,startup,shutdown}_wenv
 
     if [[ -n "$TMUX" ]]; then
         tmux set-environment WENV ''
         tmux rename-session $(tmux display-message -p '#{session_id}' | tr -d '$')
     fi
-}
-
-unset_wenv_vars() {
-    unset_quiet WENV_{DIR,DEPS}
-}
-
-source_wenv_and_run_wenv_def() {
-    [[ -z "$1" ]] && return 1
-    local wenv="$1"
-    unset_quiet -f wenv_def
-    source $WENV_CFG/wenvs/$wenv
-    if ! function_exists wenv_def; then
-        echo "wenv_def not defined for wenv '$1'" >&2
-        return 1
-    fi
-    wenv_def
 }
 
 wenv_new() {
@@ -324,7 +351,7 @@ OPTIONS
     fi
 
     mkdir -p $WENV_CFG/wenvs/$(dirname $wenv)
-    cat =(perl -pe "s|WENV_DIR=.*?$|WENV_DIR=\"$wenv_dir\"|" "$template") > "$WENV_CFG/wenvs/$wenv"
+    cat =(perl -pe "s|wenv_dir=.*?$|wenv_dir=\"$wenv_dir\"|" "$template") > "$WENV_CFG/wenvs/$wenv"
 
     wenv_edit "$wenv"
 }
@@ -420,54 +447,6 @@ OPTIONS
     eval "rm $rm_args $wenv_file"
 }
 
-wenv_source() {
-    local usage="\
-USAGE
-  wenv source [-h] [<wenv>, ...] - Source one or more wenvs + their dependencies.
-
-OPTIONS
-  -h    Display this help message.
-
-DESCRIPTION
-  \`wenv source\` sources the active wenv's aliases and its dependencies.
-"
-
-    [[ -z "$WENV" ]] && { echo "error sourcing active wenv: \$WENV is empty" >&2 ; return 1 }
-
-    local opt OPTIND
-    while getopts ":h" opt; do
-        case "$opt" in
-            h)
-                echo "$usage"
-                return 0
-                ;;
-            \?)
-                echo "unknown option: -$OPTARG" >&2
-                return 1
-                ;;
-        esac
-    done
-
-    eval "$(grep -Eho '^\s*WENV_(DIR|DEPS|EXTENSIONS)=(.*)' $WENV_CFG/wenvs/$WENV)"
-    ((${#WENV_EXTENSIONS[@]} != 0)) && wenv_extension_load "${WENV_EXTENSIONS[@]}"
-    ((${#WENV_DEPS[@]} != 0)) && source_wenv_dependencies_recursively "${WENV_DEPS[@]}"
-
-    source_wenv_and_run_wenv_def "$WENV"
-
-    return 0
-}
-
-source_wenv_dependencies_recursively() {
-    local wenv
-    for wenv in $@; do
-        # grep for the WENV_DEPS for this wenv and recursively source those
-        eval source_wenv_dependencies_recursively "$(grep -Pho '^\s*WENV_DEPS=\(\K.*(?=\))' $WENV_CFG/wenvs/$wenv)"
-        # source this wenv now that its dependencies are loaded
-        source $WENV_CFG/wenvs/$wenv
-        unset wenv_def
-    done
-}
-
 wenv_cd() {
     local usage="\
 USAGE
@@ -482,7 +461,7 @@ DESCRIPTION
 
   Calling as \`wenv cd <wenv>\` will \`cd\` into <wenv>'s base directory.
 
-  The base directory of a wenv is defined by its WENV_DIR value.
+  The base directory of a wenv is defined by its \`wenv_dir\` value.
 "
 
     local opt OPTIND
@@ -501,7 +480,7 @@ DESCRIPTION
     shift $((OPTIND-1))
 
     if [[ -z "$1" ]]; then
-        [[ ! -z "$WENV_DIR" ]] && cd "$WENV_DIR" &> /dev/null
+        [[ -n "$WENV_DIR" ]] && cd "$WENV_DIR" &> /dev/null
         return 0
     fi
 
@@ -511,7 +490,7 @@ DESCRIPTION
     fi
     local wenv="$1"
 
-    eval cd $(grep -Pho '^\s*WENV_DIR=\K.*' $WENV_CFG/wenvs/$wenv)
+    only_load_wenv_vars=1 source $WENV_CFG/wenvs/$wenv
 
     return 0
 }
@@ -590,7 +569,7 @@ DESCRIPTION
     # clear out bootstrap_wenv if we're in an active wenv
     [[ -n "$WENV" ]] && unset_quiet -f bootstrap_wenv
 
-    source_wenv_and_run_wenv_def "$wenv"
+    only_load_wenv_vars=1 source $WENV_CFG/wenvs/$wenv
     if ! function_exists bootstrap_wenv; then
         echo "bootstrap_wenv not defined for wenv '$1'" >&2
         return 1
@@ -665,7 +644,7 @@ ARGUMENTS
 DESCRIPTION
   This function sources the corresponding extension file at \$WENV_CFG/<extension>.
   This will only source the extension file in the current shell. See the
-  documentation on the WENV_EXTENSIONS environment variable for loading an
+  documentation on the \`wenv_extensions\` configuration variable for loading an
   extension in every shell of a wenv.
 "
 
