Bug fix: infinite recursion when sourcing wenvs. Remove wenv_load()

diff --git a/wenv b/wenv
--- a/wenv
+++ b/wenv
@@ -177,7 +177,8 @@ wenv_exec() {
     [[ -z "$1" ]] && return 1
     export WENV="$1"
 
-    wenv_load || return 1
+    run_wenv_def "$WENV" || { echo "wenv_def() not defined for wenv '$WENV'" >&2 ; return 1 }
+    wenv_source "$WENV" || { echo "failed to source wenv '$WENV'" >&2 ; return 1 }
 
     export ORIGINAL_PS1="$PS1"
     export PS1="($WENV) $ORIGINAL_PS1"
@@ -253,17 +254,8 @@ wenv_clean_up() {
     export PS1="$ORIGINAL_PS1"
 }
 
-# load either the input wenv, or the active WENV + its dependencies
-wenv_load() {
-    local wenv="${1:-${WENV}}"
-
-    run_wenv_def "$wenv"
-    wenv_source "$wenv"
-
-    return 0
-}
-
 load_wenv_vars() {
+    unset_wenv_vars
     run_wenv_def "$@"
     unset_quiet -f bootstrap_wenv,startup_wenv,shutdown_wenv
 }
@@ -434,13 +426,13 @@ DESCRIPTION
 source_wenvs_recursively() {
     local wenv
     for wenv in $@; do
-        ! is_wenv "$wenv" && { echo "error: '$wenv' is not a wenv" ; continue }
+        ! is_wenv "$wenv" && { echo "error: '$wenv' is not a wenv" >&2 ; continue }
         load_wenv_vars "$wenv"
         ((${#WENV_DEPS[@]} != 0)) && source_wenvs_recursively "${WENV_DEPS[@]}"
         ((${#WENV_EXTENSIONS[@]} != 0)) && wenv_extension_load "${WENV_EXTENSIONS[@]}"
         source "$WENV_CFG/wenvs/$wenv" >/dev/null
-        unset_wenv_vars
     done
+    unset_wenv_vars
 }
 
 wenv_cd() {
