Disable most of the git stuff for now.

diff --git a/wenv b/wenv
--- a/wenv
+++ b/wenv
@@ -112,28 +112,28 @@ wenv_exec() {
 
     [[ -n "$WENV_TASK" ]] && task start "$WENV_TASK" >/dev/null 2>&1
 
-    if [[ $flag_c -eq 1 ]]; then
-        if [[ -n "$WENV_GIT_DIR" ]]; then
-            # cd into git repo base dir if available. this option is available to
-            # avoid trying to cd into a dir that's only in the WENV's branch of
-            # the repo (which will fail if we're not in the branch)
-            cd "$WENV_GIT_DIR" &> /dev/null
-        else
-            cd "$WENV_DIR" &> /dev/null
-        fi
-        if [[ -n "$WENV_BRANCH" ]]; then
-            local current_branch=$(git branch | grep '*' | sed 's/* //')
-            if [[ ! -z "$current_branch" && "$WENV_BRANCH" != "$current_branch" ]]; then
-                git diff-index --quiet HEAD -- 2>/dev/null
-                # more scalable solution to the below line? don't want to just say -ne 1 because other errors may matter.
-                # also, checking for value in zsh array is ugly
-                [[ $? -ne 0 ]] && [[ $? -ne 128 ]] && { warn_uncommitted_changes "$WENV_BRANCH" ; wenv_clean_up ; return 1 }
-            fi
-            git checkout "$WENV_BRANCH"
-        fi
-        # if we previously cd'd into git repo dir, go to project dir now
-        [[ -n "$WENV_GIT_DIR" ]] && cd "$WENV_DIR" &> /dev/null
-    fi
+    # if [[ $flag_c -eq 1 ]]; then
+    #     if [[ -n "$WENV_GIT_DIR" ]]; then
+    #         # cd into git repo base dir if available. this option is available to
+    #         # avoid trying to cd into a dir that's only in the WENV's branch of
+    #         # the repo (which will fail if we're not in the branch)
+    #         cd "$WENV_GIT_DIR" &> /dev/null
+    #     else
+    #         cd "$WENV_DIR" &> /dev/null
+    #     fi
+    #     if [[ -n "$WENV_BRANCH" ]]; then
+    #         local current_branch=$(git branch | grep '*' | sed 's/* //')
+    #         if [[ ! -z "$current_branch" && "$WENV_BRANCH" != "$current_branch" ]]; then
+    #             git diff-index --quiet HEAD -- 2>/dev/null
+    #             # more scalable solution to the below line? don't want to just say -ne 1 because other errors may matter.
+    #             # also, checking for value in zsh array is ugly
+    #             [[ $? -ne 0 ]] && [[ $? -ne 128 ]] && { warn_uncommitted_changes "$WENV_BRANCH" ; wenv_clean_up ; return 1 }
+    #         fi
+    #         git checkout "$WENV_BRANCH"
+    #     fi
+    #     # if we previously cd'd into git repo dir, go to project dir now
+    #     [[ -n "$WENV_GIT_DIR" ]] && cd "$WENV_DIR" &> /dev/null
+    # fi
 
     return 0
 }
@@ -244,7 +244,7 @@ run_wenv_setup() {
 }
 
 wenv_new() {
-    local src="$WENV_DIR/wenv_template"
+    local src="$SRC/wenv/wenv_template"
     local flag_d=0
     while getopts ":di:" opt; do
         case $opt in
